// <auto-generated />
using System;
using HomeBudget.Infrastructure.Server.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeBudget.Infrastructure.Server.Persistence.Migrations
{
    [DbContext(typeof(HomeBudgetDbContext))]
    [Migration("20260717112523_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeBudget.Domain.Planning.BudgetPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("BudgetFitRisk")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DefaultCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("BudgetPlans", "planning");
                });

            modelBuilder.Entity("HomeBudget.Domain.Shared.BudgetCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "Name");

                    b.ToTable("BudgetCategories", "shared");
                });

            modelBuilder.Entity("HomeBudget.Infrastructure.Server.Identity.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique();

                    b.ToTable("UserAccounts", "auth");
                });

            modelBuilder.Entity("HomeBudget.Infrastructure.Server.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedOnUtc");

                    b.ToTable("OutboxMessages", "outbox");
                });

            modelBuilder.Entity("HomeBudget.Domain.Planning.BudgetPlan", b =>
                {
                    b.OwnsOne("HomeBudget.Domain.Shared.Money", "PlannedFinancialResult", b1 =>
                        {
                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("PlannedFinancialResultAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("PlannedFinancialResultCurrencyCode");

                            b1.HasKey("BudgetPlanId");

                            b1.ToTable("BudgetPlans", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");
                        });

                    b.OwnsOne("HomeBudget.Domain.Shared.Money", "TotalAllocatedExpenses", b1 =>
                        {
                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAllocatedExpensesAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalAllocatedExpensesCurrencyCode");

                            b1.HasKey("BudgetPlanId");

                            b1.ToTable("BudgetPlans", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");
                        });

                    b.OwnsOne("HomeBudget.Domain.Shared.Money", "TotalPlannedIncome", b1 =>
                        {
                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalPlannedIncomeAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalPlannedIncomeCurrencyCode");

                            b1.HasKey("BudgetPlanId");

                            b1.ToTable("BudgetPlans", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");
                        });

                    b.OwnsOne("HomeBudget.Domain.Shared.Money", "TotalSavingContributions", b1 =>
                        {
                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalSavingContributionsAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalSavingContributionsCurrencyCode");

                            b1.HasKey("BudgetPlanId");

                            b1.ToTable("BudgetPlans", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");
                        });

                    b.OwnsMany("HomeBudget.Domain.Planning.CategoryAllocation", "ExpenseCategoryAllocations", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("ExpenseSharePercentage")
                                .HasColumnType("numeric");

                            b1.Property<string>("Flexibility")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<decimal>("IncomeSharePercentage")
                                .HasColumnType("numeric");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetPlanId");

                            b1.ToTable("ExpenseCategoryAllocations", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");

                            b1.OwnsOne("HomeBudget.Domain.Shared.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("CategoryAllocationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("AmountAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("AmountCurrencyCode");

                                    b2.HasKey("CategoryAllocationId");

                                    b2.ToTable("ExpenseCategoryAllocations", "planning");

                                    b2.WithOwner()
                                        .HasForeignKey("CategoryAllocationId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.OwnsMany("HomeBudget.Domain.Planning.PlannedIncome", "PlannedIncomes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("ConversionDate")
                                .HasColumnType("date");

                            b1.Property<DateOnly>("ExpectedDate")
                                .HasColumnType("date");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetPlanId");

                            b1.ToTable("PlannedIncomes", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");

                            b1.OwnsOne("HomeBudget.Domain.Shared.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("PlannedIncomeId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("AmountAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("AmountCurrencyCode");

                                    b2.HasKey("PlannedIncomeId");

                                    b2.ToTable("PlannedIncomes", "planning");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedIncomeId");
                                });

                            b1.OwnsOne("HomeBudget.Domain.Shared.Money", "ConvertedAmount", b2 =>
                                {
                                    b2.Property<Guid>("PlannedIncomeId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("ConvertedAmountAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("ConvertedAmountCurrencyCode");

                                    b2.HasKey("PlannedIncomeId");

                                    b2.ToTable("PlannedIncomes", "planning");

                                    b2.WithOwner()
                                        .HasForeignKey("PlannedIncomeId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();

                            b1.Navigation("ConvertedAmount");
                        });

                    b.OwnsMany("HomeBudget.Domain.Planning.SavingContribution", "SavingContributions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("BudgetPlanId");

                            b1.ToTable("SavingContributions", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");

                            b1.OwnsOne("HomeBudget.Domain.Shared.Money", "Amount", b2 =>
                                {
                                    b2.Property<Guid>("SavingContributionId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 2)
                                        .HasColumnType("numeric(18,2)")
                                        .HasColumnName("AmountAmount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("AmountCurrencyCode");

                                    b2.HasKey("SavingContributionId");

                                    b2.ToTable("SavingContributions", "planning");

                                    b2.WithOwner()
                                        .HasForeignKey("SavingContributionId");
                                });

                            b1.Navigation("Amount")
                                .IsRequired();
                        });

                    b.OwnsOne("HomeBudget.Domain.Shared.BudgetPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("BudgetPlanId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("PeriodMonth");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("PeriodYear");

                            b1.HasKey("BudgetPlanId");

                            b1.ToTable("BudgetPlans", "planning");

                            b1.WithOwner()
                                .HasForeignKey("BudgetPlanId");
                        });

                    b.Navigation("ExpenseCategoryAllocations");

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("PlannedFinancialResult")
                        .IsRequired();

                    b.Navigation("PlannedIncomes");

                    b.Navigation("SavingContributions");

                    b.Navigation("TotalAllocatedExpenses")
                        .IsRequired();

                    b.Navigation("TotalPlannedIncome")
                        .IsRequired();

                    b.Navigation("TotalSavingContributions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
